// src/integrations/supabase/client.ts

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://crcdfnquhfovgyabnfuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyY2RmbnF1aGZvdmd5YWJuZnV2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyOTc2NTAsImV4cCI6MjA4NTg3MzY1MH0.ALchcr0FtVb4doX2ggBSruCm5d0OjBKPhfJDOSvKkXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);