// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kyfzqgyazmjtnxjdvetr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5ZnpxZ3lhem1qdG54amR2ZXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0ODIxMTgsImV4cCI6MjA4NTA1ODExOH0.553eaDnItMn5SmKb2ik3-IMj6TiT48Ef3JiNx6qRgis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);