// src/integrations/supabase/client.ts

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://kyfzqgyazmjtnxjdvetr.supabase.co";
// LƯU Ý: Khóa này có vẻ không đúng định dạng của Supabase. 
// Khóa công khai (anon key) của Supabase thường là một chuỗi JWT dài.
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_p8H73ZMxkN-vZaL661hk5A_AmZeFsKl";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);